[package]
name = "repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monke_lang_interpreter = { version = "0.1.0", path = "../monke-lang-interpreter" }
